# Configure main menu and social menu
[[main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/html/"
    [main.params]
        icon = "notebook"
        newtab = true

[[main]]
    identifier = "others"
    name = "Others"

[[main]]
    parent = "others"
    weight = 1
    identifier = "Features"
    name = "Features"
    url = "/features/"
    [main.params]
        icon = "notice/tip"
        # newtab = true

[[main]]
    parent = "others"
    identifier = "Minecraft"
    name = "Minecraft"
    url = "https://mc.sciroccogti.top"
    [main.params]
        icon = "minecraft"
        newtab = true

[[main]]
    parent = "others"
    identifier = "Pokemon"
    name = "Pokemon"
    url = "http://ps.sciroccogti.top-7653.psim.us/"
    [main.params]
        icon = "pokemon"
        newtab = true

[[main]]
    parent = "others"
    identifier = "Bangumis"
    name = "Bangumis"
    url = "/page/bangumis/"
    [main.params]
        icon = "brand-bilibili"

[[main]]
    parent = "others"
    identifier = "Tieba-Sign"
    name = "Tieba-Sign"
    url = "http://tieba.sciroccogti.top"
    [main.params]
        icon = "tieba"
        newtab = true

[[social]]
    identifier = "mail"
    name = "mail"
    url = "mailto:scirocco_gti@yeah.net"
    weight = 1
    [social.params]
        icon = "mail"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Sciroccogti"
    weight = 1
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "bilibili"
    name = "哔哩哔哩"
    url = "https://space.bilibili.com/11850306"
    weight = 2
    [social.params]
        icon = "brand-bilibili"

[[social]]
    identifier = "x"
    name = "X"
    url = "https://x.com/scirocco_gte"
    weight = 3
    [social.params]
        icon = "brand-x"

[[social]]
    identifier = "zhihu"
    name = "知乎"
    url = "https://www.zhihu.com/people/wu-feng-yin-xuan"
    weight = 3
    [social.params]
        icon = "brand-zhihu"

[[social]]
    identifier = "xlog"
    name = "xLog"
    url = "https://sciroccogti.xlog.app/portfolios"
    weight = 3
    [social.params]
        icon = "xlog"

[[social]]
    identifier = "rss"
    name = "rss"
    url = "/index.xml"
    weight = 100
    [social.params]
        icon = "rss"
