# Configure main menu and social menu
# [[main]]
#     identifier = "home"
#     name = "Home"
#     url = "/"
#     [main.params]
#         icon = "home"
#         newtab = true

[[social]]
    identifier = "mail"
    name = "mail"
    url = "mailto:scirocco_gti@yeah.net"
    weight = 1
    [social.params]
        icon = "mail"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Sciroccogti"
    weight = 1
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "bilibili"
    name = "哔哩哔哩"
    url = "https://space.bilibili.com/11850306"
    weight = 2
    [social.params]
        icon = "brand-bilibili"

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/scirocco_gte"
    weight = 3
    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "zhihu"
    name = "知乎"
    url = "https://www.zhihu.com/people/wu-feng-yin-xuan"
    weight = 3
    [social.params]
        icon = "brand-zhihu"

[[social]]
    identifier = "rss"
    name = "rss"
    url = "/index.xml"
    weight = 100
    [social.params]
        icon = "rss"
